trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
# Step to build and install the project
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'  # Points to the correct POM file at the root
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    goals: 'clean package'  # Standard goal for building and packaging the project

# Copy the JAR file to the artifact staging directory (adjust if it's not a JAR)
- task: CopyFiles@2
  inputs:
    contents: 'target/*.jar'   # Adjust if your project generates a JAR
    targetFolder: '$(Build.ArtifactStagingDirectory)'

# Publish the JAR file as an artifact
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
